# From https://github.com/detekt/detekt/blob/v1.23.7/detekt-rules-ruleauthors/src/main/resources/config/config.yml
ruleauthors:
  active: true
  UseEntityAtName:
    active: true
  ViolatesTypeResolutionRequirements:
    active: true
