# From https://github.com/detekt/detekt/blob/v1.23.7/detekt-rules-libraries/src/main/resources/config/config.yml
libraries:
  active: true
  ForbiddenPublicDataClass:
    active: true
    ignorePackages:
      - '*.internal'
      - '*.internal.*'
  LibraryCodeMustSpecifyReturnType:
    active: true
    allowOmitUnit: false
  LibraryEntitiesShouldNotBePublic:
    active: true
